name: Lint

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  stylelint:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-stylelint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          packages: 'stylelint-order stylelint-config-clean-order'
          stylelint_config: .stylelintrc.json
          stylelint_input: '**/*.css'
          fail_on_error: true
          filter_mode: diff_context

  eslint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Run eslint on changed files
        uses: tj-actions/eslint-changed-files@v18
        with:
          config_path: .eslintrc
          file_extensions: '**/*.js'
          extra_args: '--max-warnings=0'
          all_files: true
          ignore_path: .eslintignore
