name: Stylelint
on: pull_request

jobs:
  stylelint:
    name: runner / stylelint
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: stylelint
        uses: reviewdog/action-stylelint@v1
        with:
          stylelint_input: "**/*.css"
          stylelint_config: ".stylelintrc.json"
