name: reviewdog

on:
  pull_request:
    types: [synchronize, opened]

jobs:
  stylelint:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - uses: actions/checkout@v3

      - name: stylelint
        uses: reviewdog/action-stylelint@v1
        with:
          github_token: ${{ secrets.github_token }}
          fail_on_error: true
          reporter: github-pr-review
          filter_mode: "diff_context"
          stylelint_config: ".stylelintrc.json"
          stylelint_input: "**/*.css"
