name: reviewdog
on: [pull_request]

jobs:
  stylelint:
    name: runner / stylelint
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - uses: actions/checkout@v3
      - name: Run stylelint with reviewdog
        uses: reviewdog/action-stylelint@v1
        with:
          github_token: ${{ secrets.TOKEN }}
          packages: 'stylelint-config-standard stylelint-order stylelint-config-rational-order'
          reporter: github-pr-review
          stylelint_input: '**/*.css'
          stylelint_config: .stylelintrc.json
